openapi: 3.0.0
info:
  title: Post API
  description: This api is used for Post Service.
  version: 0.1.9
servers:
  - url: http://localhost:8081/blog/v1/api/
    description: This is url for local development server  
paths:
  /posts:
    get:
      summary: Returns a list of posts.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of posts
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string